// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PowerTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void power() {
    driver.get("https://www.onliner.by/");
    driver.manage().window().setSize(new Dimension(1123, 1020));
    driver.findElement(By.cssSelector(".b-main-navigation__item:nth-child(1) .b-main-navigation__text")).click();
    driver.findElement(By.cssSelector(".catalog-navigation-classifier:nth-child(4) > .catalog-navigation-classifier__item:nth-child(4)")).click();
    driver.findElement(By.xpath("//div[@id=\'container\']/div/div/div/div/div/div[4]/div/div[3]/div/div/div[2]/div")).click();
    driver.findElement(By.cssSelector(".catalog-navigation-list__aside-item_active .catalog-navigation-list__dropdown-item:nth-child(9) .catalog-navigation-list__dropdown-title")).click();
    driver.findElement(By.cssSelector(".schema-filter-control:nth-child(2) > .schema-filter__number-input_price")).click();
    driver.findElement(By.cssSelector(".schema-filter__fieldset:nth-child(7) .schema-filter-control:nth-child(1) > .schema-filter-control__item")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".schema-product__group:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".schema-product__group:nth-child(2) .schema-product__ticket-list"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("schema-products")).click();
  }
}
