// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Autobaraholka4Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void autobaraholka4() {
    driver.get("https://www.onliner.by/");
    driver.manage().window().setSize(new Dimension(1123, 1020));
    driver.findElement(By.xpath("//div[@id=\'container\']/div/div/header/div[2]/div/nav/ul/li[3]/a/span")).click();
    driver.findElement(By.cssSelector(".vehicle-form__row:nth-child(2) .vehicle-form__line:nth-child(1) .vehicle-form__line:nth-child(1) .input-style__real:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".dropdown-style__item_brand_citroen-alter .dropdown-style__checkbox-text")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".vehicle-form__offers-unit:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".vehicle-form__row:nth-child(1) .input-style__combo > .input-style__wrapper:nth-child(1) > .input-style > .input-style__real")).click();
    driver.findElement(By.cssSelector(".vehicle-form__row:nth-child(3) .input-style__wrapper:nth-child(2) > .input-style")).click();
    driver.findElement(By.cssSelector(".vehicle-form__row:nth-child(3) .input-style__wrapper:nth-child(2) > .input-style")).click();
    driver.findElement(By.cssSelector(".vehicle-form__filter-part_1")).click();
    driver.findElement(By.cssSelector(".vehicle-form__row:nth-child(3) .input-style__wrapper:nth-child(2) > .input-style")).sendKeys("20000");
  }
}
