// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class KatalogBMWTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void katalogBMW() {
    driver.get("https://www.onliner.by/");
    driver.manage().window().setSize(new Dimension(1123, 1020));
    driver.findElement(By.xpath("//div[@id=\'container\']/div/div/header/div[2]/div/nav/ul/li[3]/a/span")).click();
    driver.findElement(By.cssSelector(".project-navigation__item:nth-child(2) .project-navigation__sign")).click();
    driver.findElement(By.name("models_manufactures_id[]")).click();
    {
      WebElement dropdown = driver.findElement(By.name("models_manufactures_id[]"));
      dropdown.findElement(By.xpath("//option[. = 'BMW (31)']")).click();
    }
    driver.findElement(By.name("max-mileage")).click();
    {
      WebElement dropdown = driver.findElement(By.name("max-mileage"));
      dropdown.findElement(By.xpath("//option[. = 'До 20 000 км']")).click();
    }
    driver.findElement(By.name("country")).click();
    {
      WebElement dropdown = driver.findElement(By.name("country"));
      dropdown.findElement(By.xpath("//option[. = 'Беларусь (10)']")).click();
    }
  }
}
